rule_dir: './preprocessing/text/rule'
translate_dir: '$rule_dir/translate'
pattern_dir: '$rule_dir/pattern'
number_dir: '$rule_dir/number'
dictionary_dir: '$rule_dir/dict'

#translate
currency_to_kor: '$translate_dir/currency_to_kor.json'
engword_to_kor: '$translate_dir/engword_to_kor.json'
kor_processing: '$translate_dir/kor_processing.json'
mathsymbol_to_kor: '$translate_dir/mathsymbol_to_kor.json'
hanja1800_to_kor: '$translate_dir/hanja1800_to_kor.json'
#hangeul_measure_num: '$rule_dir/hangeul_measure_num.json'
heading: '$translate_dir/heading.json'
string_test: '$translate_dir/string_test.json'
char_translate_korean: '$translate_dir/char_translate_korean.json'
units_to_kor: '$translate_dir/units_to_kor.json'
units2_to_kor: '$translate_dir/units2_to_kor.json'
unique_word_dic: '$translate_dir/unique_word_dic.json'
hiragana_to_kor: '$translate_dir/hiragana_to_kor.json'
katagana_to_kor: '$translate_dir/katagana_to_kor.json'
english_tempdic: '$translate_dir/english_tempdic.json'
hanja_tempdic: '$translate_dir/hanja_tempdic.json'

#pattern
bankaccount_pattern: '$pattern_dir/bankaccount_pattern.csv'
date_pattern: '$pattern_dir/date_pattern.csv'
A_to_B_pattern: '$pattern_dir/A_to_B_pattern.csv'
score_pattern: '$pattern_dir/score_pattern.csv'
telephone_pattern: '$pattern_dir/telephone_pattern.csv'
time_pattern: '$pattern_dir/time_pattern.csv'
hangeulunit_pattern: '$pattern_dir/hangeulunit_pattern.csv'
incident_pattern: '$pattern_dir/incident_pattern.csv'
math_pattern: '$pattern_dir/math_pattern.csv'
brackets_pattern: '$pattern_dir/brackets_pattern.csv'
english_number_pattern: '$pattern_dir/english_number_pattern.csv'
step_read_pattern: '$pattern_dir/step_read_pattern.csv'

#dictionary
hangeul_number_measure: '$dictionary_dir/hangeul_number_measure2.csv'
hanja_number_measure: '$dictionary_dir/hanja_number_measure.csv'
incident_clue_words: '$dictionary_dir/incident_clue_words.csv'
score_related_words: '$dictionary_dir/score_related_words.csv'
step_read_words: '$dictionary_dir/step_read_words.csv'
hangulnum_dan_words: '$dictionary_dir/hangulnum_dan_dict.csv'

#number
#hangeul_kisu1: '$number_dir/hangeul_kisu1.json'
hangeul_kisu2: '$number_dir/hangeul_kisu2.json'
hanja_kisu: '$number_dir/hanja_kisu.json'
english_kisu: '$number_dir/english_kisu.json'
designnumber_to_number: '$number_dir/designnumber_to_number.json'
#hanjanumber2: '$number_dir/hanjanumber2.json'